### PR TITLE
Fix view source shows original event for an edited message

### LINKED ISSUE #376: View Source does not show the latest event when message is edited
#### Description
If I send a message and then modify it, the protocol sends two events with the `edit event` having a `m.relates_to` and `m.new_content`. It is upto the UI to render the message as edited (Which Cinny does). 
But if I click on `View Source` it is expected to view the latest event. In Cinny we are shown the original event and not the latest event when we view `View Source`.

#### Example
This is what `Cinny`` shows
```json
{
    "content": {
      "body": "I'm about to edit this message.",
      "msgtype": "m.text",
      "org.matrix.msc1767.text": "I'm about to edit this message."
    },
    "type": "m.room.message",
    "event_id": "$epV0V7xZ0cEfVy7tGgmTwGpKZCC3sGl9D4ey4AxxCWY",
  }
```

This is what `element`` shows
```json
{
  "content": {
    "body": " * I've edited the message.",
    "m.new_content": {
      "body": "I've edited the message.",
      "msgtype": "m.text",
      "org.matrix.msc1767.text": "I've edited the message."
    },
    "m.relates_to": {
      "event_id": "$epV0V7xZ0cEfVy7tGgmTwGpKZCC3sGl9D4ey4AxxCWY",
      "rel_type": "m.replace"
    },
    "msgtype": "m.text",
    "org.matrix.msc1767.text": " * I've edited the message."
  },
  "type": "m.room.message",
  "event_id": "$0oItExKSP_KUYIVqqGTFTWAh5vNB1WdD3lwUlochmYs",
}
```

#### To Reproduce
1. Send a message
2. Edit it
3. Click `View Source` for the edited message

#### Expected behavior
Show the latest event in `View Source`

#### Version
Cinny v1.8.0

### PR DESCRIPTION
**Pull request by clmnin**
Signed-off-by: Clament John <cj@hackerlab.in>

fixes #376 

### Description

When we click view source for an edited message we were showing the original event (the unedited event) instead of the latest edited event.

#### Type of change
- Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Preview: https://6230529cace91206d67467a0--pr-cinny.netlify.app
⚠️ Exercise caution. Use test accounts. ⚠️

### CODE REVIEW

File: src/app/molecules/message/Message.jsx [hunk 1]
```diff
@@ -734,7 +735,7 @@ function Message({
         {roomTimeline && !isEditing && (
           <MessageOptions
             roomTimeline={roomTimeline}
-            mEvent={mEvent}
+            mEvent={editedMEvent !== undefined ? editedMEvent : mEvent}
```
Comment (ajbura) [inline src/app/molecules/message/Message.jsx]: changing this mEvent is not a good idea as other option in menu also depend on this. If we want to get the edited message we can get it from `roomTimeline.editedTimeline` inside MessageOptions

Comment (clmnin) [reply src/app/molecules/message/Message.jsx]: I've moved the changes to `MessageOptions`. Please review the changes.

File: src/app/molecules/message/Message.jsx [hunk 2]
```diff
@@ -479,6 +479,16 @@ const MessageOptions = React.memo(({
   const myPowerlevel = room.getMember(mx.getUserId())?.powerLevel;
   const canIRedact = room.currentState.hasSufficientPowerLevelFor('redact', myPowerlevel);
   const canSendReaction = room.currentState.maySendEvent('m.reaction', mx.getUserId());
+  // check if this has an edited event in the timeline, if so, then replace
+  // View Source with editedMEvent
+  const eventId = mEvent.getId();
+  const { editedTimeline } = roomTimeline ?? {};
+  const isEdited = roomTimeline ? editedTimeline.has(eventId) : false;
```
Comment (ajbura) [inline src/app/molecules/message/Message.jsx]: this line can give an error if editedTimeline is undefined. I think we can just use `if (editedTimeline?.has(eventId))`

File: src/app/molecules/message/Message.jsx [hunk 3]
```diff
@@ -479,6 +479,16 @@ const MessageOptions = React.memo(({
   const myPowerlevel = room.getMember(mx.getUserId())?.powerLevel;
   const canIRedact = room.currentState.hasSufficientPowerLevelFor('redact', myPowerlevel);
   const canSendReaction = room.currentState.maySendEvent('m.reaction', mx.getUserId());
+  // check if this has an edited event in the timeline, if so, then replace
+  // View Source with editedMEvent
+  const eventId = mEvent.getId();
```
Comment (ajbura) [inline src/app/molecules/message/Message.jsx]: Please use `mEvent.getId()` directly as event id can change

File: src/app/molecules/message/Message.jsx [hunk 4]
```diff
@@ -516,7 +526,7 @@ const MessageOptions = React.memo(({
             </MenuItem>
             <MenuItem
               iconSrc={CmdIC}
-              onClick={() => openViewSource(mEvent)}
+              onClick={() => openViewSource(editedMEvent !== undefined ? editedMEvent : mEvent)}
```
Comment (ajbura) [inline src/app/molecules/message/Message.jsx]: creating `handleOpenViewSource` function and doing all editedMEvent finding stuff in that func and opening view source from there will be a good idea cuz then we are doing calc when we actually need them

**Comment by ajbura** [comment]
Also please use comments when absolutely necessary otherwise they create additional burden in maintenance.

File: src/app/molecules/message/Message.jsx (hunk 4 above)
Comment (clmnin) [reply src/app/molecules/message/Message.jsx]: Does react do this calc `editedMEvent !== undefined ? editedMEvent : mEvent` for each rerender? I didn't quite get why you are suggesting us to create a new function `handleOpenViewSource`.

Would be cleaner. But my question is on if we are doing unnecessary calc

Comment (ajbura) [reply src/app/molecules/message/Message.jsx]: I mean execution from line 484 to 490 on only require when user click menu item.

so we can do that in `handleOpenViewSource` and call `openViewSource` from there

**Review by ajbura — APPROVED** [review]
