### PR TITLE
Keyboard focus related bugs

### LINKED ISSUE #62: Opening Emojiboard does not focus on the input field
#### Describe the bug
When clicking on the reaction button/emojiboard icon, the focus does note move to the input field of the selector.

#### Expected behavior
When clicking on the selector, the text input focus should immediately move to the input field of the selector and when the selector is closed (by cancelling or selecting a reaction) the focus should move back to the main input field on the bottom. This ensures seamless experience when reacting to any message during a conversation even while you're writing a message.

### PR DESCRIPTION
**Pull request by ginnyTheCat**
### Description

Fixes some keyboard focus related bugs:
- [x] Focus input on emoji board opening (not on mobile)
Fixes #62
- [x] Focus the end of a message when editing
- [x] Focus search input when opening room message search
- [x] Focus member input when opening room member page (not on mobile)

#### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Preview: https://620158d3df66852adbc8dc5a--pr-cinny.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

File: src/app/molecules/room-members/RoomMembers.jsx [hunk 1]
```diff
@@ -125,6 +128,11 @@ function RoomMembers({ roomId }) {
   const [membership, setMembership] = useState('join');
   const [members] = useMemberOfMembership(roomId, membership);
   const [searchMembers, handleSearch] = useSearchMembers(members);
+  const searchRef = useRef(null);
+
+  useEffect(() => {
+    if (!settings.isTouchScreenDevice) searchRef.current.focus();
+  }, []);
```
Comment (ajbura) [inline src/app/molecules/room-members/RoomMembers.jsx]: adding [autoFocus](https://html.spec.whatwg.org/dev/interaction.html#the-autofocus-attribute) attribute in Input.jsx component will be nice as we have to create unnecessary refs if we do it with js.

File: src/app/organisms/emoji-board/EmojiBoardOpener.jsx [hunk 2]
```diff
@@ -25,7 +27,10 @@ function EmojiBoardOpener() {
 
   function afterEmojiBoardToggle(isVisible) {
     isEmojiBoardVisible = isVisible;
-    if (!isVisible) {
+    if (isVisible) {
+      searchRef.current.value = '';
+      if (!settings.isTouchScreenDevice) searchRef.current.focus();
+    } else {
```
Comment (ajbura) [inline src/app/organisms/emoji-board/EmojiBoardOpener.jsx]: autoFocus will not work in EmojiBoard so we can have it this way here. also current method only clears input and doesn't not reset search results.

**Review by ajbura — APPROVED** [review]
