### PR TITLE
Request session info from sw if missing

### LINKED ISSUE #2638: Images stop loading after a while
### Describe the bug

Since updating to 4.10.3 (and logging out & back in as recommended in the release notes) images stop loading after a short while.
Checking the server logs I see complaints about missing authentication token.
If I use the Clear Cache & Reload button images will be loaded for a short time and after a while stop again with the same missing authentication token error.

Comparing working request headers with ones that don't show they're identical:
```
GET /_matrix/client/v1/media/download/squirrel.rocks/9f279c8616d8bb817d55dfe125ab731a05e3df572017952514187460608?allow_redirect=true HTTP/2
Host: matrix.squirrel.rocks
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0
Accept: image/avif,image/webp,image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5
Accept-Language: en,de-DE;q=0.9,nl;q=0.8
Accept-Encoding: gzip, deflate, br, zstd
Referer: https://cinny.squirrel.rocks/
DNT: 1
Sec-GPC: 1
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-site
Connection: keep-alive
Cookie: __Host-nc_sameSiteCookielax=true; __Host-nc_sameSiteCookiestrict=true
Priority: u=0, i
```
Only difference is the time passed after the client loads, eventually media requests will fail:
```
Feb 16 17:55:43 media_repo[3255490]: time="2026-02-16 16:55:43.491 Z" level=info msg="Replying with result: *_responses.ErrorResponse &{Code:M_MISSING_TOKEN Message:no token provided (required) InternalCode:M_MISSING_TOKEN}" contentLength=0 contentType="" host=squirrel.rocks method=GET queryString="allow_redirect=true" remoteAddr="127.0.0.1:44270" requestId=REQ-218 resource=/_matrix/client/v1/media/download/squirrel.rocks/9f279c8616d8bb817d55dfe125ab731a05e3df572017952514187460608 userAgent="Mozilla/5.0 (X11; Linux x86_64; rv:147.0) Gecko/20100101 Firefox/147.0"
```

### Reproduction

1. Log in to Cinny 4.10.3
2. Let the session idle for some time
3. Switch between rooms / spaces
4. Avatars / images will no longer load

### Expected behavior

Avatars / images continue to load

### Platform and versions

```shell
OS: openSUSE Tumbleweed
Browser: Firefox 147.0.3
Cinny version: 4.10.3
Homeserver: squirrel.rocks (Dendrite 0.15.2, MMR 1.3.8)
```

### Additional context

Things worked fine before the update + logging out & back in.

### PR DESCRIPTION
**Pull request by ajbura**
### Description

Fixes #2638

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

File: src/sw.ts [hunk 1]
```diff
@@ -71,11 +122,21 @@ function fetchConfig(token: string): RequestInit {
...
+
+  if (!session) {
+    event.waitUntil(
+      (async () => {
+        session = await requestSessionWithTimeout(clientId);
+      })()
+    );
+  }
+
   if (!session) return;
```
Comment (mmmykhailo) [inline src/sw.ts]: This seems confusing to me because as I understand `waitUntil` will just happen asynchronously and session won't be updated **before** the next `if`

**Review by mmmykhailo — CHANGES_REQUESTED** [review]
I was able to reproduce the issue
Image

File: src/sw.ts (hunk 1 above)
Comment (ajbura) [reply src/sw.ts]: thanks for pointing out.

**Comment by xetem** [comment]
I've been using this PR all day today and yesterday and have not experienced any issues, so anecdotally this seems to be fixing the bug.

**Review by kfiven — APPROVED** [review]
