### PR TITLE
Prevent crash when opening room permission on conduit homeserver

### LINKED ISSUE #310: Cinny fails to load room permissions tab [Conduit server]
Cinny fails to load room permissions for rooms hosted on Conduit server.

Scenario:

1. Create a new Room on Conduit server
2. Navigate to Permissions tab
3. Observe error in RoomPermissions.jsx: Line: 258

#### Screenshots
image

- Cinny 1.7.0
- Tested: Docker version and local build
- homeserver: [ Conduit 0.3.0 ]

### PR DESCRIPTION
**Pull request by ginnyTheCat**
### Description

This prevents the room permission tab from crashing Cinny on the Conduit homeserver by showing the default power levels if the homeserver does not include it in its response.

Fixes #310

#### Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

Preview: https://620a70c20c5bd51abd924e29--pr-cinny.netlify.app
⚠️ Do you trust the author of this PR? Maybe this build will steal your keys or give you malware. Exercise caution. Use test accounts.

### CODE REVIEW

File: src/app/molecules/room-permissions/RoomPermissions.jsx [hunk 1]
```diff
@@ -233,8 +233,9 @@ function RoomPermissions({ roomId }) {
 
                   let powerLevel = 0;
                   let permValue = permInfo.parent
-                    ? permissions[permInfo.parent][permKey]
```
Comment (ajbura) [inline src/app/molecules/room-permissions/RoomPermissions.jsx:236]: Optional chaining in permissions[permInfo.parent]`?.`[permKey] can do the job as line 240 already handle default value.

**Review by ajbura — CHANGES_REQUESTED** [review]

File: src/app/molecules/room-permissions/RoomPermissions.jsx (hunk 1 above)
Comment (ginnyTheCat) [reply src/app/molecules/room-permissions/RoomPermissions.jsx:236]: that would've been too easy :sweat_smile:

**Review by ajbura — APPROVED** [review]
