### PR TITLE
Fix 'enter' immediately sending the message using IME keyboard on Safari

### LINKED ISSUE #2103: When in Japanese input, 'enter' should not immediately send the message
### Describe the bug

In Japanese IME, you typically type text, then hit enter to "commit" the correct Kanji. For example, if I type テスト then it will be underlined until I hit 'enter', in effect confirming that I've finished writing and picked the correct Kanji/characters

Cinny binds to enter, so even though I am not done typing and only committed a word, as soon as I hit enter, Cinny sends the message 

It's a very common problem when using `onkeyup` as listener, eg: https://stackoverflow.com/questions/46812908/enter-keyup-event-in-japanese-input

### Reproduction

_No response_

### Expected behavior

_No response_

### Platform and versions

```shell
macOS Desktop 4.2.3, macOS 15.2
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by programmablereya**
### Description

On most browsers, pressing Enter to end IME composition produces this sequence of events:
* keydown (keycode 229, key Processing/Unidentified, isComposing true)
* compositionend
* keyup (keycode 13, key Enter, isComposing false)

On Safari, the sequence is different:
* compositionend
* keydown (keycode 229, key Enter, isComposing false)
* keyup (keycode 13, key Enter, isComposing false)

This causes Safari users to mistakenly send their messages when they press Enter to confirm their choice in an IME.

The workaround is to treat the next keydown with keycode 229 as if it were part of the IME composition period if it occurs within a short time of the compositionend event.

Fixes #2103, but needs confirmation from a Safari user.

#### Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by programmablereya** [comment]
I have read the CLA Document and I hereby sign the CLA

File: src/app/organisms/settings/Settings.jsx [hunk 1]
```diff
@@ -47,6 +47,7 @@ import { settingsAtom } from '../../state/settings';
 import { isMacOS } from '../../utils/user-agent';
 import { KeySymbol } from '../../utils/key-symbol';
 import { useMatrixClient } from '../../hooks/useMatrixClient';
+import { isComposing } from '../../utils/keyboard.js';
```
Comment (dvcrn) [inline src/app/organisms/settings/Settings.jsx]:
```suggestion
import { isComposing } from '../../utils/keyboard;
```

File: src/app/organisms/search/Search.jsx [hunk 2]
```diff
@@ -27,6 +27,7 @@ import { useKeyDown } from '../../hooks/useKeyDown';
 import { openSearch } from '../../../client/action/navigation';
 import { useMatrixClient } from '../../hooks/useMatrixClient';
 import { factoryRoomIdByActivity } from '../../utils/sort';
+import { isComposing } from '../../utils/keyboard.js';
```
Comment (dvcrn) [inline src/app/organisms/search/Search.jsx]:
```suggestion
import { isComposing } from '../../utils/keyboard';
```

**Review by dvcrn — COMMENTED** [review]
Pathes for these 2 imports is incorrect so it can't get resolved properly 

Besides that, this PR fixes IME errors for me. I can type in Japanese normally ❤️

**Comment by dvcrn** [comment]
I've merged this into my fork of Cinny https://github.com/dvcrn/davids-cinny/releases/tag/v4.4.0

File: src/app/utils/keyboard.ts [hunk 3]
```diff
@@ -11,23 +12,36 @@ export interface KeyboardEventLike {
...
-  if (isKeyHotkey('tab', evt)) {
+  if (!isComposing(evt) && isKeyHotkey('tab', evt)) {
     evt.preventDefault();
     callback();
   }
 };
 
 export const preventScrollWithArrowKey: KeyboardEventHandler = (evt) => {
-  if (isKeyHotkey(['arrowup', 'arrowright', 'arrowdown', 'arrowleft'], evt)) {
+  if (!isComposing(evt.nativeEvent) && isKeyHotkey(['arrowup', 'arrowright', 'arrowdown', 'arrowleft'], evt)) {
```
Comment (BLumia) [inline src/app/utils/keyboard.ts]: Is this change necessary? I've tested it with Chrome + Chinese IME and try to press arrow keys while composing, and it seems this change is not needed. Or maybe I missed something?

File: src/app/pages/auth/ServerPicker.tsx [hunk 4]
```diff
@@ -53,6 +53,9 @@ export function ServerPicker({
   };
 
   const handleKeyDown: KeyboardEventHandler<HTMLInputElement> = (evt) => {
+    if (isComposing(evt.nativeEvent)) {
```
Comment (BLumia) [inline src/app/pages/auth/ServerPicker.tsx]: Shouldn't this (and also some other `isComposing()` calls) be `isComposing(evt)` instead?

File: src/app/hooks/useSafariCompositionTaggingForKeyDown.ts [hunk 5]
```diff
@@ -0,0 +1,33 @@
...
+
+    function recordCompositionEnd(evt: CompositionEvent) {
+      compositionJustEndedAt = evt.timeStamp
+    }
+
+    function interceptAndTagKeyDown(evt: KeyboardEvent) {
+      if (compositionJustEndedAt !== null
+        && evt.keyCode === 229
+        && (evt.timeStamp - compositionJustEndedAt) < compositionEndThreshold) {
+        Object.assign(evt, { [actuallyComposingTag]: true })
```
Comment (ajbura) [inline src/app/hooks/useSafariCompositionTaggingForKeyDown.ts]: `actuallyComposingTag` is the variable outside the scope of this hook and is side effect, the `actuallyComposingTag` variable is a good candidate for the /app/state as atom if you want to retain state and available throughout app.

File: src/app/utils/keyboard.ts [hunk 6]
```diff
@@ -1,5 +1,6 @@
 import { isKeyHotkey } from 'is-hotkey';
 import { KeyboardEventHandler } from 'react';
+import { isTaggedAsComposing } from '../hooks/useSafariCompositionTaggingForKeyDown';
```
Comment (ajbura) [inline src/app/utils/keyboard.ts]: importing from hooks to utils is discouraged to prevent any unknown circular dependencies formation. will be a good idea to pass the data to this func as arguments.

**Review by ajbura — CHANGES_REQUESTED** [review]
Apart from the requested changes is it really needed to check for it everywhere listening to keyboard event as the original issue only request for fix in the message editor specifically?

**Comment by programmablereya** [comment]
Total overhaul to make a much smaller change that uses atoms - how does this look?

File: src/app/state/lastCompositionEnd.ts [hunk 7]
```diff
@@ -0,0 +1,3 @@
+import { atom } from 'jotai';
+
+export const lastCompositionEndAtom = atom<number>(Number.NEGATIVE_INFINITY);
```
Comment (ajbura) [inline src/app/state/lastCompositionEnd.ts]: since we do not know the initial value could we set it to `undefined`

**Review by ajbura — CHANGES_REQUESTED** [review]
Looks good overall. Thanks for the changes!

File: src/app/state/lastCompositionEnd.ts (hunk 7 above)
Comment (programmablereya) [reply src/app/state/lastCompositionEnd.ts]: It is done!

**Review by kfiven — APPROVED** [review]

**Review by ajbura — CHANGES_REQUESTED** [review]
Can you please prettify your change as it seems they are not prettified? It will create unnecessary changes for other contributors who work with prettier.

**Comment by programmablereya** [comment]
> Can you please prettify your change as it seems they are not prettified? It will create unnecessary changes for other contributors who work with prettier.

Done.

**Review by ajbura — APPROVED** [review]
LGTM. Thanks!
